// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct PositionData {
  int32 col;
  int32 row;
}

library Position {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "arcadia", name: "Position", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x74626172636164696100000000000000506f736974696f6e0000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0008020004040000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (int32, int32)
  Schema constant _valueSchema = Schema.wrap(0x0008020023230000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "hexId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "col";
    fieldNames[1] = "row";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get col.
   */
  function getCol(bytes32 hexId) internal view returns (int32 col) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get col.
   */
  function _getCol(bytes32 hexId) internal view returns (int32 col) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set col.
   */
  function setCol(bytes32 hexId, int32 col) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((col)), _fieldLayout);
  }

  /**
   * @notice Set col.
   */
  function _setCol(bytes32 hexId, int32 col) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((col)), _fieldLayout);
  }

  /**
   * @notice Get row.
   */
  function getRow(bytes32 hexId) internal view returns (int32 row) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get row.
   */
  function _getRow(bytes32 hexId) internal view returns (int32 row) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set row.
   */
  function setRow(bytes32 hexId, int32 row) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((row)), _fieldLayout);
  }

  /**
   * @notice Set row.
   */
  function _setRow(bytes32 hexId, int32 row) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((row)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 hexId) internal view returns (PositionData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 hexId) internal view returns (PositionData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 hexId, int32 col, int32 row) internal {
    bytes memory _staticData = encodeStatic(col, row);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 hexId, int32 col, int32 row) internal {
    bytes memory _staticData = encodeStatic(col, row);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 hexId, PositionData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.col, _table.row);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 hexId, PositionData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.col, _table.row);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (int32 col, int32 row) {
    col = (int32(uint32(Bytes.getBytes4(_blob, 0))));

    row = (int32(uint32(Bytes.getBytes4(_blob, 4))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (PositionData memory _table) {
    (_table.col, _table.row) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 hexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 hexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(int32 col, int32 row) internal pure returns (bytes memory) {
    return abi.encodePacked(col, row);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(int32 col, int32 row) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(col, row);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 hexId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    return _keyTuple;
  }
}
