// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Position, PositionData } from "./tables/Position.sol";
import { Terrain, TerrainData } from "./tables/Terrain.sol";
import { ProvinceProvision, ProvinceProvisionData } from "./tables/ProvinceProvision.sol";
import { TerritoryStat, TerritoryStatData } from "./tables/TerritoryStat.sol";
import { RouteCost, RouteCostData } from "./tables/RouteCost.sol";
import { TransportMultiplier } from "./tables/TransportMultiplier.sol";
import { Simulation, SimulationData } from "./tables/Simulation.sol";
import { LandOwnership } from "./tables/LandOwnership.sol";
import { AccessControl } from "./tables/AccessControl.sol";
import { LandSecurity } from "./tables/LandSecurity.sol";
import { SoulLocation } from "./tables/SoulLocation.sol";
import { AssetLocation } from "./tables/AssetLocation.sol";
