// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct SimulationData {
  uint32 currentYear;
  uint8 currentSeason;
}

library Simulation {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "sengoku", name: "Simulation", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746273656e676f6b750000000000000053696d756c6174696f6e000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0005020004010000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint32, uint8)
  Schema constant _valueSchema = Schema.wrap(0x0005020003000000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "worldId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "currentYear";
    fieldNames[1] = "currentSeason";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get currentYear.
   */
  function getCurrentYear(bytes32 worldId) internal view returns (uint32 currentYear) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Get currentYear.
   */
  function _getCurrentYear(bytes32 worldId) internal view returns (uint32 currentYear) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint32(bytes4(_blob)));
  }

  /**
   * @notice Set currentYear.
   */
  function setCurrentYear(bytes32 worldId, uint32 currentYear) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((currentYear)), _fieldLayout);
  }

  /**
   * @notice Set currentYear.
   */
  function _setCurrentYear(bytes32 worldId, uint32 currentYear) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((currentYear)), _fieldLayout);
  }

  /**
   * @notice Get currentSeason.
   */
  function getCurrentSeason(bytes32 worldId) internal view returns (uint8 currentSeason) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get currentSeason.
   */
  function _getCurrentSeason(bytes32 worldId) internal view returns (uint8 currentSeason) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set currentSeason.
   */
  function setCurrentSeason(bytes32 worldId, uint8 currentSeason) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((currentSeason)), _fieldLayout);
  }

  /**
   * @notice Set currentSeason.
   */
  function _setCurrentSeason(bytes32 worldId, uint8 currentSeason) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((currentSeason)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 worldId) internal view returns (SimulationData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 worldId) internal view returns (SimulationData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 worldId, uint32 currentYear, uint8 currentSeason) internal {
    bytes memory _staticData = encodeStatic(currentYear, currentSeason);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 worldId, uint32 currentYear, uint8 currentSeason) internal {
    bytes memory _staticData = encodeStatic(currentYear, currentSeason);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 worldId, SimulationData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.currentYear, _table.currentSeason);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 worldId, SimulationData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.currentYear, _table.currentSeason);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint32 currentYear, uint8 currentSeason) {
    currentYear = (uint32(Bytes.getBytes4(_blob, 0)));

    currentSeason = (uint8(Bytes.getBytes1(_blob, 4)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (SimulationData memory _table) {
    (_table.currentYear, _table.currentSeason) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 worldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 worldId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint32 currentYear, uint8 currentSeason) internal pure returns (bytes memory) {
    return abi.encodePacked(currentYear, currentSeason);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint32 currentYear,
    uint8 currentSeason
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(currentYear, currentSeason);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 worldId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = worldId;

    return _keyTuple;
  }
}
