// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct TerrainData {
  uint8 terrainType;
  int32 elevation;
}

library Terrain {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "sengoku", name: "Terrain", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746273656e676f6b75000000000000005465727261696e000000000000000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0005020001040000000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint8, int32)
  Schema constant _valueSchema = Schema.wrap(0x0005020000230000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "hexId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](2);
    fieldNames[0] = "terrainType";
    fieldNames[1] = "elevation";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get terrainType.
   */
  function getTerrainType(bytes32 hexId) internal view returns (uint8 terrainType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get terrainType.
   */
  function _getTerrainType(bytes32 hexId) internal view returns (uint8 terrainType) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set terrainType.
   */
  function setTerrainType(bytes32 hexId, uint8 terrainType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((terrainType)), _fieldLayout);
  }

  /**
   * @notice Set terrainType.
   */
  function _setTerrainType(bytes32 hexId, uint8 terrainType) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((terrainType)), _fieldLayout);
  }

  /**
   * @notice Get elevation.
   */
  function getElevation(bytes32 hexId) internal view returns (int32 elevation) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Get elevation.
   */
  function _getElevation(bytes32 hexId) internal view returns (int32 elevation) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (int32(uint32(bytes4(_blob))));
  }

  /**
   * @notice Set elevation.
   */
  function setElevation(bytes32 hexId, int32 elevation) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((elevation)), _fieldLayout);
  }

  /**
   * @notice Set elevation.
   */
  function _setElevation(bytes32 hexId, int32 elevation) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((elevation)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 hexId) internal view returns (TerrainData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 hexId) internal view returns (TerrainData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 hexId, uint8 terrainType, int32 elevation) internal {
    bytes memory _staticData = encodeStatic(terrainType, elevation);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 hexId, uint8 terrainType, int32 elevation) internal {
    bytes memory _staticData = encodeStatic(terrainType, elevation);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 hexId, TerrainData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.terrainType, _table.elevation);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 hexId, TerrainData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.terrainType, _table.elevation);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(bytes memory _blob) internal pure returns (uint8 terrainType, int32 elevation) {
    terrainType = (uint8(Bytes.getBytes1(_blob, 0)));

    elevation = (int32(uint32(Bytes.getBytes4(_blob, 1))));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (TerrainData memory _table) {
    (_table.terrainType, _table.elevation) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 hexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 hexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint8 terrainType, int32 elevation) internal pure returns (bytes memory) {
    return abi.encodePacked(terrainType, elevation);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint8 terrainType,
    int32 elevation
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(terrainType, elevation);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 hexId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    return _keyTuple;
  }
}
