// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

// Import store internals
import { IStore } from "@latticexyz/store/src/IStore.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";
import { StoreCore } from "@latticexyz/store/src/StoreCore.sol";
import { Bytes } from "@latticexyz/store/src/Bytes.sol";
import { Memory } from "@latticexyz/store/src/Memory.sol";
import { SliceLib } from "@latticexyz/store/src/Slice.sol";
import { EncodeArray } from "@latticexyz/store/src/tightcoder/EncodeArray.sol";
import { FieldLayout } from "@latticexyz/store/src/FieldLayout.sol";
import { Schema } from "@latticexyz/store/src/Schema.sol";
import { EncodedLengths, EncodedLengthsLib } from "@latticexyz/store/src/EncodedLengths.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";

struct TerritoryStatData {
  uint256 kokudaka;
  uint256 population;
  uint8 stability;
}

library TerritoryStat {
  // Hex below is the result of `WorldResourceIdLib.encode({ namespace: "sengoku", name: "TerritoryStat", typeId: RESOURCE_TABLE });`
  ResourceId constant _tableId = ResourceId.wrap(0x746273656e676f6b75000000000000005465727269746f727953746174000000);

  FieldLayout constant _fieldLayout =
    FieldLayout.wrap(0x0041030020200100000000000000000000000000000000000000000000000000);

  // Hex-encoded key schema of (bytes32)
  Schema constant _keySchema = Schema.wrap(0x002001005f000000000000000000000000000000000000000000000000000000);
  // Hex-encoded value schema of (uint256, uint256, uint8)
  Schema constant _valueSchema = Schema.wrap(0x004103001f1f0000000000000000000000000000000000000000000000000000);

  /**
   * @notice Get the table's key field names.
   * @return keyNames An array of strings with the names of key fields.
   */
  function getKeyNames() internal pure returns (string[] memory keyNames) {
    keyNames = new string[](1);
    keyNames[0] = "hexId";
  }

  /**
   * @notice Get the table's value field names.
   * @return fieldNames An array of strings with the names of value fields.
   */
  function getFieldNames() internal pure returns (string[] memory fieldNames) {
    fieldNames = new string[](3);
    fieldNames[0] = "kokudaka";
    fieldNames[1] = "population";
    fieldNames[2] = "stability";
  }

  /**
   * @notice Register the table with its config.
   */
  function register() internal {
    StoreSwitch.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Register the table with its config.
   */
  function _register() internal {
    StoreCore.registerTable(_tableId, _fieldLayout, _keySchema, _valueSchema, getKeyNames(), getFieldNames());
  }

  /**
   * @notice Get kokudaka.
   */
  function getKokudaka(bytes32 hexId) internal view returns (uint256 kokudaka) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get kokudaka.
   */
  function _getKokudaka(bytes32 hexId) internal view returns (uint256 kokudaka) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 0, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set kokudaka.
   */
  function setKokudaka(bytes32 hexId, uint256 kokudaka) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((kokudaka)), _fieldLayout);
  }

  /**
   * @notice Set kokudaka.
   */
  function _setKokudaka(bytes32 hexId, uint256 kokudaka) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setStaticField(_tableId, _keyTuple, 0, abi.encodePacked((kokudaka)), _fieldLayout);
  }

  /**
   * @notice Get population.
   */
  function getPopulation(bytes32 hexId) internal view returns (uint256 population) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Get population.
   */
  function _getPopulation(bytes32 hexId) internal view returns (uint256 population) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 1, _fieldLayout);
    return (uint256(bytes32(_blob)));
  }

  /**
   * @notice Set population.
   */
  function setPopulation(bytes32 hexId, uint256 population) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((population)), _fieldLayout);
  }

  /**
   * @notice Set population.
   */
  function _setPopulation(bytes32 hexId, uint256 population) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setStaticField(_tableId, _keyTuple, 1, abi.encodePacked((population)), _fieldLayout);
  }

  /**
   * @notice Get stability.
   */
  function getStability(bytes32 hexId) internal view returns (uint8 stability) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreSwitch.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Get stability.
   */
  function _getStability(bytes32 hexId) internal view returns (uint8 stability) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    bytes32 _blob = StoreCore.getStaticField(_tableId, _keyTuple, 2, _fieldLayout);
    return (uint8(bytes1(_blob)));
  }

  /**
   * @notice Set stability.
   */
  function setStability(bytes32 hexId, uint8 stability) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((stability)), _fieldLayout);
  }

  /**
   * @notice Set stability.
   */
  function _setStability(bytes32 hexId, uint8 stability) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setStaticField(_tableId, _keyTuple, 2, abi.encodePacked((stability)), _fieldLayout);
  }

  /**
   * @notice Get the full data.
   */
  function get(bytes32 hexId) internal view returns (TerritoryStatData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreSwitch.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Get the full data.
   */
  function _get(bytes32 hexId) internal view returns (TerritoryStatData memory _table) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    (bytes memory _staticData, EncodedLengths _encodedLengths, bytes memory _dynamicData) = StoreCore.getRecord(
      _tableId,
      _keyTuple,
      _fieldLayout
    );
    return decode(_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function set(bytes32 hexId, uint256 kokudaka, uint256 population, uint8 stability) internal {
    bytes memory _staticData = encodeStatic(kokudaka, population, stability);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using individual values.
   */
  function _set(bytes32 hexId, uint256 kokudaka, uint256 population, uint8 stability) internal {
    bytes memory _staticData = encodeStatic(kokudaka, population, stability);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function set(bytes32 hexId, TerritoryStatData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.kokudaka, _table.population, _table.stability);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Set the full data using the data struct.
   */
  function _set(bytes32 hexId, TerritoryStatData memory _table) internal {
    bytes memory _staticData = encodeStatic(_table.kokudaka, _table.population, _table.stability);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.setRecord(_tableId, _keyTuple, _staticData, _encodedLengths, _dynamicData, _fieldLayout);
  }

  /**
   * @notice Decode the tightly packed blob of static data using this table's field layout.
   */
  function decodeStatic(
    bytes memory _blob
  ) internal pure returns (uint256 kokudaka, uint256 population, uint8 stability) {
    kokudaka = (uint256(Bytes.getBytes32(_blob, 0)));

    population = (uint256(Bytes.getBytes32(_blob, 32)));

    stability = (uint8(Bytes.getBytes1(_blob, 64)));
  }

  /**
   * @notice Decode the tightly packed blobs using this table's field layout.
   * @param _staticData Tightly packed static fields.
   *
   *
   */
  function decode(
    bytes memory _staticData,
    EncodedLengths,
    bytes memory
  ) internal pure returns (TerritoryStatData memory _table) {
    (_table.kokudaka, _table.population, _table.stability) = decodeStatic(_staticData);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function deleteRecord(bytes32 hexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreSwitch.deleteRecord(_tableId, _keyTuple);
  }

  /**
   * @notice Delete all data for given keys.
   */
  function _deleteRecord(bytes32 hexId) internal {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    StoreCore.deleteRecord(_tableId, _keyTuple, _fieldLayout);
  }

  /**
   * @notice Tightly pack static (fixed length) data using this table's schema.
   * @return The static data, encoded into a sequence of bytes.
   */
  function encodeStatic(uint256 kokudaka, uint256 population, uint8 stability) internal pure returns (bytes memory) {
    return abi.encodePacked(kokudaka, population, stability);
  }

  /**
   * @notice Encode all of a record's fields.
   * @return The static (fixed length) data, encoded into a sequence of bytes.
   * @return The lengths of the dynamic fields (packed into a single bytes32 value).
   * @return The dynamic (variable length) data, encoded into a sequence of bytes.
   */
  function encode(
    uint256 kokudaka,
    uint256 population,
    uint8 stability
  ) internal pure returns (bytes memory, EncodedLengths, bytes memory) {
    bytes memory _staticData = encodeStatic(kokudaka, population, stability);

    EncodedLengths _encodedLengths;
    bytes memory _dynamicData;

    return (_staticData, _encodedLengths, _dynamicData);
  }

  /**
   * @notice Encode keys as a bytes32 array using this table's field layout.
   */
  function encodeKeyTuple(bytes32 hexId) internal pure returns (bytes32[] memory) {
    bytes32[] memory _keyTuple = new bytes32[](1);
    _keyTuple[0] = hexId;

    return _keyTuple;
  }
}
